import mongoose from "mongoose";

const PanelSchema = new mongoose.Schema(
  {
    id: { type: String, required: true },          // UUID generated by client
    gridId: { type: String, required: true },      // <-- REQUIRED for multi-grid
    containerId: { type: String, required: true }, // points to container
    type: { type: String, default: "taskbox" },
    row: { type: Number, default: 0 },
    col: { type: Number, default: 0 },
    width: { type: Number, default: 1 },
    height: { type: Number, default: 1 },
    userId: { type: String, required: true },
    props: { type: mongoose.Schema.Types.Mixed, default: {} }
  },
  { timestamps: true }
);

export default mongoose.model("Panel", PanelSchema);
